name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  quality-assurance:
    name: Quality Assurance
    uses: ./.github/workflows/integration.yaml

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test step
      run: |
        echo 'xD'