name: Django webserver CI/CD

on:
  push:
    branches: [ "main" ]

concurrency:
  group: main
  cancel-in-progress: true

jobs:

  integration:
    name: Quality Assurance
    uses: ./.github/workflows/integration.yaml

  deploy:
    name: Deploy code to AWS EC2 instance
    needs: integration
    runs-on: ubuntu-latest
    steps:
    - name: Configure SSH connection
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/github
        chmod 600 ~/.ssh/github
        cat >>~/.ssh/config <<END
        Host target
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/github
          LogLevel ERROR
          StrictHostKeyChecking no
        END
    - name: Run deploy commands
      run: |
        ssh target "cd django-saas/ && docker-compose down && git pull && docker-compose build && docker-compose up -d --force-recreate"