name: Integration

on: [pull_request, workflow_call]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dev dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
    - name: Lint code with flake8
      run: |
        flake8 src
    - name: Install project dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
    - name: Testing landing page app
      run: |
          python src/manage.py test landing
    - name: Testing CLI app
      run: |
        python src/manage.py test cli